name: Run remark-cli
description: Markdown processor
author: tj-actions
inputs:
  plugins:
    description: 'List of [remarkjs plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md).'
    required: true
    default: |
      remark-toc
  files:
    description: ' List of input markdown files '
    required: true
    default: |
      README.md
      README.md
  args:
    description: '[remark cli](https://github.com/unifiedjs/unified-args#cli) options.'
    required: true
    default: "-r /.remarkrc.json --use toc --output"

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: file-text
  color: white
